name: Daily BriefBot

on:
  schedule:
    - cron: '0 8 * * *'  # every day at 8:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: cache
          key: briefbot-cache
      - name: Run BriefBot
        run: python main.py
        env:
          MISTRAL_KEY: ${{ secrets.MISTRAL_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          SENDER: ${{ secrets.SENDER }}
          EMAIL: ${{ secrets.EMAIL }}
      - name: Save updated cache
        uses: actions/cache/save@v4
        with:
          path: cache
          key: briefbot-cache
