name: Daily BriefBot

on:
  schedule:
    - cron: '0 8 * * *'  # every day at 8:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download politics_cache artifact
        uses: actions/download-artifact@v4
        with:
          name: politics_cache
          path: cache
      - name: Download tech_cache artifact
        uses: actions/download-artifact@v4
        with:
          name: tech_cache
          path: cache
      - name: Run BriefBot
        run: python main.py
        env:
          MISTRAL_KEY: ${{ secrets.MISTRAL_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          SENDER: ${{ secrets.SENDER }}
          EMAIL: ${{ secrets.EMAIL }}
      - name: Upload politics_cache
        uses: actions/upload-artifact@v4
        with:
          name: politics_cache
          path: cache/politics_cache.json
      - name: Upload tech_cache
        uses: actions/upload-artifact@v4
        with:
          name: tech_cache
          path: cache/tech_cache.json
